### PR TITLE
bump to lts-18 and fix ordering issue in snapshot diff

### LINKED ISSUE #315: `stackage.org/diff/` shows some updates as delete+add
E.g. https://www.stackage.org/diff/nightly-2022-11-17/nightly-2023-03-31 shows `BNFC` and others as deleted and added rather than as updated.  
Screenshot 2023-03-31 at 10 22 08
How come, and is this intended?

Also, e.g. `BNFC-meta` and `Boolean` have no visible diff in this listing, should they be mentioned at all?

P.S.: Hope this is the right repo to report this issue against; got here from
- https://github.com/commercialhaskell/stackage-content/issues/132

### PR DESCRIPTION
**Pull request by juhp**
closes #315 and rebases deps to lts-18

Actually untested (since I was lazy to setup pq) but credit goes to @alaendle for pointing out the suspect code.

### CODE REVIEW

File: src/Stackage/Snapshot/Diff.hs [hunk 1]
```diff
@@ -77,7 +77,7 @@ snapshotDiff
 snapshotDiff as0 bs0 =
     SnapshotDiff $ map (second VersionChange) $ go (sortEm as0) (sortEm bs0)
   where
-    sortEm = sortOn (toCaseFold . textDisplay . fst)
+    sortEm = sortOn (textDisplay . fst)
```
Comment (andreasabel) [inline src/Stackage/Snapshot/Diff.hs:80]: This is still not obviously correct, as we sort on `textDisplay` but then compare later without it.
Is`textDisplay` necessary here?

NB: Will the order change by removing `toCaseFold` so that packages with capital letters come first, and then the lowercase ones?  This might not be desirable...

Comment (juhp) [reply src/Stackage/Snapshot/Diff.hs:80]: Thank you, good point

Comment (juhp) [reply src/Stackage/Snapshot/Diff.hs]: I took your approach

**Review by andreasabel — APPROVED** [review]

**Comment by juhp** [comment]
@snoyberg when you have time, can you have a look please? thanks

**Comment by juhp** [comment]
Thanks!
